var editorLang={
	"CN":{
		"head":{
			welcome:"欢迎"
		},
		"nav":{
			pic:"图片",
			original:"原作",
		},
		"selector":{
			search:"搜索",
			txtHolder:"作者姓名",
			searchCount:"查询数量"

		},
		"goodlist":{
			title:"标题",
			beBack:"被退回",
			download:"下载",
			upload:"上传",
			authorTag:"作者标签",
			normalTag:"小编标签",
			tagScore:"标签评分",
			authorDesc:"作者描述",
			editor:"编辑人",
			author:"作者",
			country:"国家",
			submit:"提交",
			verifyNoPass:"审核不通过"
		}
	},
	"US":{
		"head":{
			welcome:"welcome"
		},
		"nav":{
			pic:"picture",
			original:"original",
		},
		"selector":{
			search:"search",
			txtHolder:"author name",
			searchCount:"query count"
		},
		"goodlist":{
			title:"标题",
			beBack:"被退回",
			download:"下载",
			upload:"上传",
			authorTag:"作者标签",
			normalTag:"小编标签",
			tagScore:"标签评分",
			authorDesc:"作者描述",
			editor:"编辑人",
			author:"作者",
			country:"国家",
			submit:"提交",
			verifyNoPass:"审核不通过"
		}
	}
};